INSERT INTO series (title, author_id, subgenre_id) VALUES ("Twilight", 1, 3);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Hello", 2, 2);
INSERT INTO books (title, year, series_id) VALUES ("adfes", 12321, 7);
INSERT INTO books (title, year, series_id) VALUES ("gshh", 4556, 5);
INSERT INTO books (title, year, series_id) VALUES ("adsfvbg", 134, 3);
INSERT INTO books (title, year, series_id) VALUES ("hhg", 12, 9);
INSERT INTO books (title, year, series_id) VALUES ("aasdafdg", 321, 2);
INSERT INTO books (title, year, series_id) VALUES ("adfesfsghg", 1241, 3);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO characters (name, motto, species, author_id, series_id) VALUES (NULL, NULL, NULL, NULL, NULL);
INSERT INTO subgenres (name) VALUES ("sdaf");
INSERT INTO subgenres (name) VALUES ("asdfds");
INSERT INTO authors (name) VALUES ("sdaf");
INSERT INTO authors (name) VALUES ("sdaf");
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);
INSERT INTO character_books (character_id, book_id) VALUES (12, 56);